language: python
python:
- '2.7'
install:
- pip install -e .
- pip install git+http://github.com/fnielsen/afinn.git
script: py.test
env:
  global:
  - test: testing789
  - secure: GSjt5flwVVdFCaqskzU7b+15bWtufsjqWDFfMtZeYUV8KB4DXP8jMFW2y14g9RSm0VWa6ayFeqRVDb1dr+uUZjYq/nkzKAKtV62RtXi2I1gZpy3D3Ju79D6OU20ce2Fku6slcQLH1J36jlMBwxRSYPJwNNlWI0TeV4zMB6dcRQATIkznsmY0JKTaXb8KE7hkdswEhbZpt4oxD0h2KDFL9ajexT7jhWqVB5Jhb9su/D/+wQQkSNqNXMsBZnKDHwuWC8+SG7qwbZGpdyyXLxIk03YRZLhpFOat4ya44jZjufWYQtWA5VoUyToEXZcwKVaIXOfcsTR9p6HMFOvGtu6JaGw/g5FnGu9M2bF5UY6L7impvPwSRDHPFV+EdRCli/FFOTbZLpJxMn4GYJzPU77iwmkXqW806AkdaMBGTgw19oEyuQYMs9n420W9dM1h03/JUIHCw+XHjDW1N0kn18c7e0XLIglLmNi1M4Ms7A2rf4LWG9WP9cgJfwRG4TnL1jdGyhIr4/TaWyf3yDGJ73hpE6U/2l/3Vlo1pFL28qVVAM8ajS5EPFaubdKNdo8+GLpE11rSgbIqYlF2GP3vQZ1tMJR0I3ETqtPhTiC+38PTMq/cPhK9f4akJg+QS5jwiZcmV3ugbGJfJKy4H1LmGN6GLmGNWfUL1J+6UIVQfpnJ75M=
deploy:
  provider: heroku
  api_key:
    secure: EdHMmtZl/8+bzCTm5/ekupjVWHJ0dN5yp3xmCh0REFOHWdeD2KtRVqZssdrfmtO2S1+7buthhfRq1ay1OvQ0fI1V9x7f1VSEwhBa5ig1e6xdqmMtplHvNm/TFJeyqSNY+p3xPx5fTJiWlTQyQDreGd3+g6muMwYZ5+Z9sErluzY=
  app: map-world-news
  on:
    repo: rkuykendall/map-world-news
after_deploy:
- npm install
- git remote set-url origin "https://${GH_TOKEN}@github.com/rkuykendall/map-world-news.git"
- git config --global user.email "robert@rkuykendall.com"
- git config --global user.name "Travis-CI"
- gulp deploy
sudo: false
