language: python
python:
- '2.7'
install:
- pip install -e .
- pip install git+http://github.com/fnielsen/afinn.git
script: py.test
env:
  global:
  - secure: HDaMwy2GZTN6p2sE30yzdEAws4qHiUbRqXn1Bi5tzZ4La8FzTPn8uyay1bVpjxMmngl3d/0oA2G5/qvgjsfkcHkShxYDYF1l1q6VgDdsRnFpnE2AMn6b6llZcJXWZXgBX+Vs4I/ScWtb3DQ09hJqjIu895xMje75xx1K0Sw4yQs=
deploy:
  provider: heroku
  api_key:
    secure: EdHMmtZl/8+bzCTm5/ekupjVWHJ0dN5yp3xmCh0REFOHWdeD2KtRVqZssdrfmtO2S1+7buthhfRq1ay1OvQ0fI1V9x7f1VSEwhBa5ig1e6xdqmMtplHvNm/TFJeyqSNY+p3xPx5fTJiWlTQyQDreGd3+g6muMwYZ5+Z9sErluzY=
  app: map-world-news
  on:
    repo: rkuykendall/map-world-news
after_deploy:
- npm install
- gulp pack
- git remote set-url origin "https://${GH_TOKEN}@github.com/rkuykendall/map-world-news.git"
- git config --global user.email "robert@rkuykendall.com"
- git config --global user.name "Travis-CI"
- gulp deploy
sudo: false
